[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/3d"
  to = "/landing-ai.html"
  status = 301

[[redirects]]
  from = "/landing"
  to = "/landing-simple.html"
  status = 301

[[redirects]]
  from = "/ai"
  to = "/landing-ai.html"
  status = 301

[dev]
  command = "python3 -m http.server 8080"
  port = 8080
  publish = "."
